language: go
go:
    - 1.8.x
    - 1.10.x
go_import_path: github.com/cellcycle/go-web3
sudo: false
before_install:
    - sudo apt-get install software-properties-common -y -qq
    - sudo add-apt-repository -y ppa:ethereum/ethereum
    - sudo apt-get update -qq
install:
    - sudo apt-get install ethereum -y -qq
before_script:
    - geth --dev --ws --ws.addr 0.0.0.0 --ws.origins="*" --http --http.addr 0.0.0.0 --http.api admin,debug,web3,eth,txpool,personal,clique,miner,net --mine --ws.api admin,debug,web3,eth,txpool,personal,clique,miner,net --allow-insecure-unlock &
    - sleep 5
script:
    - go test -v ./test/...
